### ISSUE TITLE
Username validation or send failure error

### ISSUE THREAD

**Issue by nicoleslaw** [18F/dolores-landingham-bot#157]
I'm not sure how hard this would be, but Dolores should let us know if a username is failing to receive messages. I added @amandaschonfeld's initial username when she joined Slack, and then she changed it—I didn't know the messages weren't coming through until she DMed me asking what happened and I realized the name change wasn't throwing an error etc.

**Comment by jessieay** [comment]
Steps for completing this:

1) Figure out if we can update an employee's slackusername in our system with it is changed on slack

if above is not possible: 
1) Figure out what error is thrown when we attempt to send a slack message to an invalid username
2) Surface that error to app admins -- perhaps via a daily email? Or maybe we should just set up newrelic instead and let that notify us? https://github.com/18F/dolores-landingham-bot/issues/21

**Comment by jrmils89** [comment]
Hey all. So I took an approach here that it would probably be better to send out slack messages using the slack user id (which shouldn't change when a username is change) instead of raising errors on bad slack usernames. I started working on this and realized it's a fairly substantial change.

I think I covered everything, and it's all housed here: https://github.com/jrmils89/dolores-landingham-bot/commits/use-slack-user-ids. I know this wasn't the exact purpose of this issue, so I thought it'd be a good idea to add a comment here, and you guys could let me know how you'd like me to proceed (pull request, make changes, do nothing since it's out of the scope of the ticket). If anything, it's an interesting exercise and hopefully saved some people time from doing this research themselves. 

I would have liked to test this with a larger dev DB to test backwards compatibility, but it should work going backwards (in theory).

A small note. Messages seem to actually be posted using the channel id as opposed to the username. It seems to me what likely happened here is that between being added to dolores and the first message being sent, the username was changed. Now the user id is being set on save, and the channel id is set based on the slack user id. It would probably be pretty simple to (now that the user id is saved on creating the user) to check for username updates when an email gets sent (or daily, or whenever makes sense).

**Comment by jessieay** [comment]
@jrmils89 sendings message via Slack ID instead of username is a GREAT idea. We're still gonna want to add users via Slack username since that is more user-friendly, but I think using something that is unique and unchanging is super ideal. Love that idea.

Depending on how much work it is, I'd suggest you do this in 2 steps:

1. Save slack user ids and use those to send messages
2. Figure out a way to routinely check that slack usernames haven't changed and if they have, update them. Perhaps a daily cron job using Clock (which we are already using)? This is less important but it seems like a good idea to have the usernames in our system match the ones on Sack.

**Comment by jrmils89** [comment]
So #1 is already done. Just an explanation of how it works:
- You still create the user by their slackname, but now it looks up their slack user id when it does that and saves it along with their username to the DB
- When you send a message, if the slack user id isn't already saved, it tries to add it by looking the employee up by their slackname
- Once it has a slack user id, it then looks up their channel based on the user id and posts to that channel (this behavior isn't different, it's just using the user id to look up the channel as opposed to the slack name)

#2 I haven't done, but I agree it would probably be a good idea. Assuming it properly finds the slack user id the first time it won't particularly matter, but just as a matter of cleaning things up I think it seems like a good idea.

I'll submit the pull request for number one and you guys can review the changes and see if there are other things you'd like to add. Not sure if/when I'd have time to do #2 quite yet

**Comment by awfrancisco** [comment]
@jrmils89 This issue can be closed right?

**Comment by jrmils89** [comment]
Yep! 👍
