### ISSUE TITLE
Add tagging support to scheduled messages

### ISSUE THREAD

**Issue by melodykramer** [18F/dolores-landingham-bot#28]
Not for MVP:

Way for messages to be tagged so that people can sign up for specific types of messages: i.e. refresher on benefits (receive all benefits msgs.)

**Comment by jessieay** [comment]
Closing in favor of https://trello.com/c/MrJuYar8

**Comment by ccostino** [comment]
Are there any concerns with using the acts_as_taggable_on gem to support this?

https://github.com/mbleigh/acts-as-taggable-on

**Comment by jessieay** [comment]
Nope, sounds good to me. 

I think there are 2 steps to this:

1) Allow people creating a scheduled message to tag the message
2) Create some kind of mechanism where people can subscribe to a tag. Would need to discuss further with someone (probably Melody/Andrew) about that because I am guessing we wouldn't want to spread out the messages in the same way for subscribers that we do for newbies. Perhaps a secondary ordering system for topic subscribers...would have to think further about this

**Comment by ccostino** [comment]
Agreed - I wonder if we should split this out into two tickets?  Add support for the tagging itself in this one and then developing the mechanism for folks to subscribe in another?  That second step might require similar permissions work as with #53 and establishing preference management within the app itself.

**Comment by jessieay** [comment]
@ccostino yeah, feel free to split!

**Comment by jessieay** [comment]
@ccostino moving this GH issue back to next up - I see #66 is about allowing users to subscribe to specific tagged messages. What about just letting users view all messages with a specific tag first?
