### ISSUE TITLE
Bullet initializer?

### ISSUE THREAD

**Issue by jessieay** [18F/dolores-landingham-bot#43]
Seems like a Bullet initializer made it in somehow - do we want to include that in every environment? Seems like a tool we should use locally to find N+1 queries but perhaps not needed to run on prod. Thoughts?

https://github.com/flyerhzm/bullet#configuration

**Comment by gemfarmer** [comment]
@jessieay  I added it when I was emulating C2's omniauth application. I had previously tried to remove it, but something errored out. I probably conflated that error with another edit, because I tested the app without it now and _clear skies ahead_. I don't think we need it in any environment right now.

tl;dr Can be removed.

**Comment by jessieay** [comment]
Closing in favor of https://trello.com/c/8aaUmwHj
