### ISSUE TITLE
Allow time in addition to days after hire?

### ISSUE THREAD

**Issue by melodykramer** [18F/dolores-landingham-bot#76]
We could make messages much shorter if we could post multiple times in a day. One way to do this is to say "What time would you like to post this?" 

Considerations: time zones, DST, Arizona (which has wacky DST rules)

**Comment by ccostino** [comment]
@melodykramer and @jessieay:  I was thinking about this a bit more, and one solution I came up with to solve the disparity with time zones is that we could store that info with the rest of the employee info (along with their started on date) so that we could always send a message at their local time.  In other words we would be able to just set a time, e.g., 10:00 AM, on a scheduled message and the message would be sent at 10:00 AM local time for any given user.  This way folks on in the PST time zone wouldn't be getting their messages at 7:00 AM, for instance. :-)

Does this sound like a good approach?  It would appear that we'd need to add support for a timezone option to the employees, a time value for scheduled messages, and then do some enhancements to the message sender.

**Comment by melodykramer** [comment]
This would be an excellent approach. (And useful for other things too.)

**Comment by ccostino** [comment]
Great, thanks @melodykramer!

@jessieay and @gemfarmer:  I'm reading conflicting things about whether or not to set the default time zone in the application.  My take is that it reduces the probability of date/time related weirdness by not accounting for what the server's time is set.  If it's set in the app then it can be deployed anywhere without concern for this as we can expect it to behave consistently.

Do either of you have any thoughts or strong feelings about this?  I wanted to check before just setting this in the app.

**Comment by melodykramer** [comment]
One thing I was thinking about this morning - I don't want these notes to show up on the weekends. And it's going to get REALLY hard to determine holiday Mondays . I'm not sure how to fix this, but thought I would bring it up in this thread. I think it's much harder to think "Oh, that's for day 104" than to think "That's for the 4th Friday in their second Month."

**Comment by ccostino** [comment]
@melodykramer:  Hmmm, really good point about that.  On the one hand, any messages sent while you're offline will be there when you login again, but I can imagine it would be easy to miss those messages as well.

I'd tackle this in a separate issue which I can create, but thank you for bringing this up, it is something worth keeping in mind!
