### ISSUE TITLE
Ability for current employees to receiving onboarding messages.

### ISSUE THREAD

**Issue by melodykramer** [18F/dolores-landingham-bot#9]
Several current 18F employees have asked if there's a way they can cycle through whatever we're giving to new hires. This feels like it might involve several steps (and shouldn't be in the MVP - just documenting this here.)

1. Saving messages that are sent to new employees.
2. Allowing current employees to say "I'd like to pretend tomorrow is Day 1" and start receiving messages.

**Comment by jessieay** [comment]
@melodykramer the good news is that `2` is super easy - we decided that rather than worrying about hooking into the Team API, we would have an input form for Slack username and start date within the Dolores Bot front end interface. The form looks like this:

![screen shot 2015-09-21 at 9 20 31 am](https://cloud.githubusercontent.com/assets/601515/9997618/0b14f00c-6042-11e5-9730-5533fc5d5a38.png)

So, anyone can add themselves as a new employee with a fake start date at any time. 

I think I need some clarification on `1`: in what way do you want to save the messages? We are already saving them in a database so that they can be sent to new employees. Would you like them saved in some other way?

**Comment by melodykramer** [comment]
Oh! That's great @jessieay.

I think you've covered both questions in this answer.

**Comment by jessieay** [comment]
Great, will close this issue since it seems the app's current implementation will address this use case :tangerine:
