### ISSUE TITLE
missing 12pm ET message from Dolores

### ISSUE THREAD

**Issue by annahsebok** [18F/dolores-landingham-bot#99]
@ccostino posted in #general-talk that folks who signed up to receive messages from @mrs_landingham were supposed to get them at 12 PM local time (whichever time zone you are in) today. I DID hear from @mrs_landingham today, but at 3:44pm and not at 12pm. My Timezone in tock is set to EST, so not sure why it didn’t come at 12pm EST. The text from her message was as follows:

Everyone at 18F must complete certain mandatory trainings, but you also have the opportunity to request optional training that will help you achieve your career goals and advance the 18F mission. The optional training can take place in a class, at a conference, or in a variety of settings.

(If you have any questions, please reach out in #conferences.)

Step One: Identify training as part of your individual professional development - (IDP)

Meet with your supervisor to discuss your training needs.
Add (or confirm) that the training event is a part of your Individual Development Plan (IDP) (https://insite.gsa.gov/portal/category/533326) If not, add it.
To update your IDP, visit the IDP tool. (https://gsa--c.na1.visual.force.com/apex/IDP_ViewPage?sfdc.tabName=01r30000001L8lz) This will open your personal IDP template. Follow instructions to complete your IDP.

Step Two: Submit your training request for higher approval

Enter complete training request into 18F Speaking Requests / Attending Events spreadsheet (https://docs.google.com/spreadsheets/d/1Y0336rKQ4FiTFhoQynRjoVuJFzXEgaV0QcHqaNd-Eis/edit#gid=2072167708) -- except Columns B (Aaron/Hillary Approval), C (Red Flag) and O (Other Red Flags); P (Steps to Approval if Red Flags) and Q (Steps to Approval).

Step Three

Reviews and Resolve any red flags identified by Pia Scott, our Training and Development Director, in the 18F Speaker Request spreadsheet.

If the training requires payment, proceed to Step Four

Step Four

Complete a SF-182, http://www.gsa.gov/portal/forms/download/117002

NOTE:  Please Do Not Enter your Social Security Number (Section A, Block 2). This will reduce your PII security risk.  

Submit your approved IDP and SF-182 to 18F to Pia Scott who will arrange for payment by Team Ops.

Step Five

If training provided at a conference and/or requires travel, a Salesforce approval request will be submitted on your behalf by the Training and Development Director.

Salesforce will generate the GSA officials’ approval or disapproval notifications.

Pia will notify you about approval status

Step Six

If travel is required, you have to submit authorization for travel. Instructions for that process are here: https://github.com/18F/handbook/blob/staging/articles/travel.md
To learn more about IDP development, please visit https://insite.gsa.gov/portal/mediaId/615682/fileName/EmployeesGuide2IndivDevePlan_1113.action

**Comment by ccostino** [comment]
Hi @annahsebok!  The reason you received the message at 3:44 PM instead of 12:00 PM is because there was a bug yesterday that prevented some messages from going out at the time they were scheduled to go out.  The fix didn't get deployed until about 3:40 PM (EST) yesterday, and as a part of the fix it was setup to send any outstanding messages that hadn't been sent already, hence the reason why it arrived at 3:44 PM.

Now that said, it would appear that all messages got sent first thing this morning, so there is still an issue with this.  I am going to close this issue in favor of opening another one that more accurately describes the new problem that happened this morning.  Thank you for taking the time to report the behavior though, it is helpful in getting this nailed down to work as expected!
